using CommandPrompterServer.Models.Dao;
using CommandPrompterServer.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CommandPrompterServer.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class UserController : Controller
    {
        private IUserService _userService { get; set; }

        /// <summary>
        /// The id of user is autogenerated, id in user is not used.
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        [HttpPut]
        [Route("AddUser")]
        [AllowAnonymous]
        public User AddNewUser([FromBody] User user)
        {
            var ret = _userService.AddNewUser(user);
            ret.Password = "********";
            return ret;
        }

        [HttpPut]
        [Route("ValidateUserInfo")]
        [Authorize]
        public bool ValidateUser([FromBody] User user)
        {
            return _userService.ValidateUser(user.Username, user.Password) == null ? false : true;
        }

        [HttpGet]
        [Route("ActivateUser/{id}")]
        [Authorize]
        public void ActivateUser(string id)
        {
            _userService.ActivateUser(id);
        }

        [HttpGet]
        [Route("DeactivateUser/{id}")]
        [Authorize]
        public void DeactivateUser(string id)
        {
            _userService.DeactivateUser(id);
        }

        [HttpPut]
        [Route("UpdateUser")]
        [Authorize]
        public User UpdateUser([FromBody] User user)
        {
            var temp = _userService.UpdateUser(user);
            temp.Password = "********";
            return temp;
        }

    }
}
