using AutoMapper;
using CommandPrompterServer.Models.Dao;
using CommandPrompterServer.Models.Dto;
using CommandPrompterServer.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CommandPrompterServer.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class UserController : Controller
    {
        private IUserService _userService { get; set; }
        private IMapper _mapper { get; set; }
        /// <summary>
        /// The id of user is autogenerated, id in user is not used.
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        [HttpPut]
        [Route("AddUser")]
        [AllowAnonymous]
        public UserResponseDto AddUser([FromBody] UserRequestDto user)
        {

            var ret = _userService.AddNewEntity(_mapper.Map<User>(user));
            
            return _mapper.Map<UserResponseDto>(ret);
        }

        [HttpPut]
        [Route("ValidateUserInfo")]
        [Authorize]
        public bool ValidateUser([FromBody] UserRequestDto user)
        {
            return _userService.ValidateUser(user.Username, user.Password) == null ? false : true;
        }

        [HttpGet]
        [Route("ActivateUser/{id}")]
        [Authorize]
        public void ActivateUser(string id)
        {
            _userService.ActivateUser(id);
        }

        [HttpGet]
        [Route("DeactivateUser/{id}")]
        [Authorize]
        public void DeactivateUser(string id)
        {
            _userService.DeactivateUser(id);
        }

        [HttpPost]
        [Route("UpdateUser")]
        [Authorize]
        public UserResponseDto UpdateUser([FromBody] UserUpdateRequestDto request)
        {
            var user = _userService.ValidateUser(request.Username, request.OldPassword);
            if (user != null)
            {
                user.Password = request.NewPassword;
                user.Email = request.Email;
                var temp = _userService.UpdateEntity(user);
            }
            return _mapper.Map<UserResponseDto>(user);
        }

    }
}
